### ISSUE TITLE
Improve detection in WSL

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#17]
![image](https://github.com/LivacoNew/CrabFetch/assets/6134068/dca64dcf-1394-42fb-91f5-3e85c2bba18a)

1. crabfetch fails to detect the resolution and refresh rate, while `wayland-info` reports it correctly
```
interface: 'wl_output',                                  version:  3, name: 11
        x: 0, y: 0, scale: 1,
        physical_width: 0 mm, physical_height: 0 mm,
        make: 'weston', model: 'rdp',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 2560 px, height: 1440 px, refresh: 60.000 Hz,
                flags: current preferred
```
2. Host is reported as Unknown. Since WSL is a virtual machine, report `WSL` should be OK.
3. WSL does't have desktop environment.
4. Terminal is reported as `init`. I thinks crabfetch incorrectly detect `/sbin/init` as terminal.
5. Although WSL can use systemd, it's not enabled in my machine. It should report `init` as detected by the terminal readout.

**Comment by LivacoNew** [comment]
I don't care about WSL tbh, I only care about actual Linux distros and not Window's weird emulation frankenstein of it.  
The only thing here I actually care about is the resolution failure, and that's only because your pointing out that `wayland-info` is working. This means that there's a valid wayland compositor that somehow CrabFetch can't connect to. Please try to disable suppressed errors and let me know what it says. 

As for the rest;
> Host is reported as Unknown.
> Terminal is reported as init.
All of this is WSL specific stuff, therefore I don't care.

> WSL does't have desktop environment.
Hence why it reports as unknown?

> Although WSL can use systemd, it's not enabled in my machine.
Check what /sbin/init symlinks to, as that's how CrabFetch detects the init system.

**Comment by CarterLi** [comment]
> I don't care about WSL tbh

**Comment by LivacoNew** [comment]
Had to install a Windows 11 VM for some ETS modding stuff a few days ago, so have decided to re-open this for better support while I have it. Here's how support looks right now from latest `3b2676f`;

![image](https://github.com/user-attachments/assets/f163e454-4b23-40f5-bfc3-f091adaef0a8)

To-Fix:
- [ ] CPU Freq is NaN
- [ ] Useless Disks (potentially already fixed by my other planned change)
- [ ] Displays are unable to find Model/Make or DRM name
- [ ] Host is Unknown
- [ ] Desktop is Unknown (Decide whether to report as Windows or keep as Unknown?)
- [ ] Terminal is Unknown
- [ ] Shell is Unknown

**Comment by CarterLi** [comment]
GPU is missing
Init system is wrong

**Comment by LivacoNew** [comment]
> GPU is missing

This is probably just cus it's a VM? Don't have any bare metal Windows machines to test otherwise, and `lspci` reveals no GPU-looking devices attached.

![image](https://github.com/user-attachments/assets/724c4410-e0e2-442b-8a85-c1877485b074)


> Init system is wrong

Shouldn't be, [systemd is apparently the default](https://learn.microsoft.com/en-us/windows/wsl/systemd) & your FastFetch is also reporting systemd

![image](https://github.com/user-attachments/assets/3896d2f9-8532-41bd-b3eb-e6607fc1dccd)

**Comment by CarterLi** [comment]
systemd in WSL is optional. You can disable it in /etc/wsl.conf

**Comment by LivacoNew** [comment]
> systemd in WSL is optional. You can disable it in /etc/wsl.conf

I'm replicating this now, ty.

**Comment by LivacoNew** [comment]
Most issues seem to now be fixed from my testing, still got the useless mounts but that's a general CrabFetch problem that I still need to fix by blocking non-physical device mounts (will likely do later tonight after I post this comment)

![image](https://github.com/user-attachments/assets/741bb26a-a5c8-44b5-bd86-7bb83455f74c)

Some notes just to clear up confusion;
- Displays can find the resolution through the wayland compositor, but no DRM name or EDID. I can still get a make/model through the compositor, but it's just WLSG's weird virtual make/model so I've decided to just discard it all and put N/A and leave it up to the user to remove the placeholders.
- The N/A in Host is the chassis type, as I don't see a way to find that in WSL.
- I don't know of any way to get the Windows Terminal version through WSL, so N/A there too.
- Init system version is unknown as it's Window's own stuff.
- Will likely add a WSL specific default config to prevent these unknowns from being shoved in the users face to deal with right off with bat. Also gives me a reason to make a proper system for per-os deafults for Android too.
- CPU Frequency wasn't a WSL problem but a VM problem from infoflags.

Will leave this issue open until the mounts are fixed, hopefully soon. Will close via the mounts commit once it has been done.

**Comment by LivacoNew** [comment]
![image](https://github.com/user-attachments/assets/12b717d7-c748-40d4-8f25-0f889ca3948a)

**Comment by CarterLi** [comment]
> Init system version is unknown as it's Window's own stuff.

This suggests that you don't know what sysvinit is. You didn't even have the basic knowledge of what is init system used for, hence you looked for `/sbin/init` instead of looking for pid 1.

**Comment by LivacoNew** [comment]
> This suggests that you don't know what sysvinit is. You didn't even have the basic knowledge of what is init system used for

Correct, while I knew about the basics of an init system, I didn't know what sysvinit was nor that the init system was guaranteed to run as PID 0. I've only been using Linux for about a year and, as I've said to you many times, have only been delving into it's low-levelness for a few months as a result of this project which was initially only to learn Rust. Your wording this like it's supposed to be an insult to me somehow?

> Please learn things carefully before copying features from fastfetch.

I didn't "copy" this detection from FastFetch, if you look in the impl you can see where I actually got it from.

![image](https://github.com/user-attachments/assets/83b9b68f-a166-4bd0-ae93-8f8b09904495)

Don't assume I copy straight from your project. I find it much more interesting to research and find stuff out myself, only using other projects as last ditch resort to know *where* to look for myself (which I rarely let myself do).

**Comment by CarterLi** [comment]
> Your wording this like it's supposed to be an insult to me somehow?

I was telling the truth.

> I didn't "copy" this detection from FastFetch, if you look in the impl you can see where I actually got it from.

Yeah I knew it. I didn't say you copy **code** from fastfetch but I said **features**. Fastfetch [uses pid 1](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/modules/initsystem/initsystem.c#L16) from day one. If you copied code from fastfetch you would have did it correctly.

Chassis detection is another feature you **copied** from fastfetch. Am I correct?

**Comment by LivacoNew** [comment]
> I was telling the truth.

Mhm, in a condescending way. 

> Chassis detection is another feature you copied from fastfetch. Am I correct?

Yes, I got the idea from the FastFetch module. 
But, and this isn't an attempt at aggression, but what's the problem with doing so that you have to make a point out of it..? Fetch scripts can't really do much in the way of originality I'm afraid, your going to see copying from one fetch script to the other, and I'm not the only one that does it.

**Comment by CarterLi** [comment]
> Fetch scripts can't really do much in the way of originality I'm afraid, your going to see copying from one fetch script to the other, and I'm not the only one that does it.

Correct. Most features of fastfetch are copied from neofetch. What makes me feel bad is that you copied features from fastfetch, with things did completely wrong, and shouted **FASTFETCH IS YUCKY and MINE IS FASTER**. Please don't do that.

**Comment by LivacoNew** [comment]
First off, I am sorry if I've made you feel bad. I'm aware my writing style makes me sound naturally aggressive, which combined with my push for CrabFetch may make it seem worse. But, please do trust me when I say I don't intend to be. It's something I'm aware of but unfortunately can't help.
Same applies for describing FastFetch as "yucky", I don't actually think it's bad at all, It's mostly just that personally I don't find it as intuitive or easy to use as others. It was added as an off-handed opinion of mine to help answer the question in the FAQ, nothing more. I'll change the wording after this I post this reply. 
I _will_ keep advertising CrabFetch as being faster however. It's one of my prouder points in this project and, unlike my description of FastFetch, there are benchmarks to prove it at least. 

As for doing things completely wrong, I can't really say anything other than to redirect you to my previous comments, in that I'm still learning all this stuff and don't want to just go copy and pasting other peoples implementations. CrabFetch is still unstable and very broken, I know. I also understand why it may be frustrating. Unfortunately, it takes time to figure out how to things better, and this project's helping with that at least.

**Comment by CarterLi** [comment]
> there are benchmarks to prove it at least

Can you elaborate? Which module crab is faster?

**Comment by LivacoNew** [comment]
> What if I didn't tell you that?

Then I would have kept ignorantly doing it, and hence why I'm happy to have you reporting issues & helping on this project <3
