### ISSUE TITLE
Add Android Support

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#19]
Dont know if you care it

![Screenshot_2024-07-12-12-06-24-178_com termux](https://github.com/user-attachments/assets/b9a5459b-9ffe-4593-bb38-c234d8d60cae)

Crabfetch fails to report most things and CPU freq is wrong too (the same issue as asahi)

**Comment by LivacoNew** [comment]
Did some research, didn't actually know you could do this shit without rooting your phone, neat.  
Installed Termux and added to my to-do list for 0.4.1 along with the other few distros. Will update once I have more to share. :)

**Comment by LivacoNew** [comment]
Did you remove the Linux check? Just to see if this is a Samsung only thing or not as your phone went through fine.
![SmartSelect_20240712_052615_Termux.jpg](https://github.com/user-attachments/assets/25cc29d8-6a52-4405-a5ac-656d87b86c36)

**Comment by CarterLi** [comment]
Crabfetch said it was not linux. It was definitely wrong so I removed the check.

**Comment by LivacoNew** [comment]
Okay good to know. Just to be clear that's rust's [std::env::consts](https://doc.rust-lang.org/std/env/consts/constant.OS.html) reporting as Android, where I'm only checking for `linux`.

**Comment by LivacoNew** [comment]
This is how support's looking now;
![image](https://github.com/user-attachments/assets/24e5d468-ee82-42b0-8724-be3528be7e38)

It's still very early, likely very broken, but it will do for the next release. Will do more testing with different emulators and phone setups.  
FastFetch is also faster than CrabFetch but again I'm fine with releasing as-is for now and working on this later to give some love to other features too.

**Comment by CarterLi** [comment]
Thanks!

What does fastfetch print?

**Comment by LivacoNew** [comment]
> Thanks!
> 
> What does fastfetch print?

![Screenshot_20240715_150614_Termux.jpg](https://github.com/user-attachments/assets/16bf92b0-d683-470d-9f94-3f69e1e64f26)

Custom config for modules/version detection. No idea wtf your ASCII's doing

**Comment by CarterLi** [comment]
Seems the CPU freq and thread count was wrong

The [official spec reads](https://www.qualcomm.com/products/mobile/snapdragon/smartphones/snapdragon-8-series-mobile-platforms/snapdragon-8-gen-2-mobile-platform) "Clock Speed: Up to 3.36 GHz"

**Comment by LivacoNew** [comment]
> Seems the CPU freq and thread count of crabfetch were wrong

Thread count just needs to be set to `1`, as there's no other way I can find to get this info so I'm simply counting cores instead. Frequency on the other hand I was not expecting. 

> On my smart phone none of the disks show my internal storage size. Instead, crabfetsh shows some strange disks.

There's tons of strange disks on mine as well, just that I filtered them out and hoped for the best. Will need to either find some docs on the other possibilities and make a better default ignore list, or find out if there's a universal way to filter out useless mounts as a whole as it's an issue CrabFetch suffers from overall. 

> The shell name seems strange too

Noticed this with mine but wasn't sure if the `-l` appendix was just bash or for everything. Again, need to find some better docs for what this `-l` is and if I'm safe to just outright remove it.

**Comment by CarterLi** [comment]
Why do you need libz and libsqlite3 on Android? It prevents crabfetch from running in adb.

![image](https://github.com/user-attachments/assets/6a794419-cfcf-426c-8b59-55aa41465e7b)

**Comment by LivacoNew** [comment]
> False. There's no way that thread count is less than physical core count.

As in 1 thread for each 8 cores, not 1 thread across the entire system lol

> In addition, there are actually smart phone CPUs that support hyper-threading.

News to me, more documentation digging for me in that case.

> There's no way you don't know what -l stands for after you did all of these features.

Less that I didn't know about it and more-so forgot about it, then when checking `/proc/{pid}/cmdline` it comes out as a single word `bash-l`, making me think it's a process called `bash-l`, not `bash -l`.  Since my other computers didn't have this when reading that file, I assumed more android weird stuff was happening.

![image](https://github.com/user-attachments/assets/f0bac851-725d-4d2d-81bb-0fae1f39c03d)

After some light reading (googling), turns out this file separates arguments with null and not whitespace which goes against my expectation of it being whitespace like all the other shenanigans, and makes a lot more sense. Mystery solved, will patch soon today.

![image](https://github.com/user-attachments/assets/fff4da03-8a40-432c-a90c-79a099c3fed3)

**Comment by LivacoNew** [comment]
CPU frequency is fixed, turns out I was parsing correct but I had my phone's performance plan on "Light" as I was running out of battery at work a few weeks ago and never turned it off.

Threads and Shell stuff should also now be fixed.

> Why do you need libz and libsqlite3 on Android? It prevents crabfetch from running in adb.

Can remove libsqlite3 easily as it's a Fedora only dep, another feature flag it is. No idea why libz is there though, as I'm not linked against it on my system?

![image](https://github.com/user-attachments/assets/2f7bc44f-f368-4c65-8ad3-c425b66069ec)

**Comment by LivacoNew** [comment]
Oh and I can tell you right now ADB will be broken even once CrabFetch is running lol, will take a peep soon as the only other stuff on my to-do list for 0.4.1 is some cleanup and docs I don't wanna make.

**Comment by LivacoNew** [comment]
Give it a shot without the `rpm_packages` flag now from latest git, should unlink libsqlite3.
