### ISSUE TITLE
Can you fix these issues?

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#7]
<img width="1160" alt="image" src="https://github.com/LivacoNew/CrabFetch/assets/6134068/980a20de-4468-4f76-9455-8858b33c6748">

**Comment by CarterLi** [comment]
https://github.com/CarterLi/fetch-bench/actions/runs/8801027817/job/24153455963#step:8:5

**Comment by LivacoNew** [comment]
GPU/Display I would class as "intentional", as they won't exist in a runner - Would put it up to the user to remove the module/placeholder more than anything being "broken" as it does technically detect right.
CPU has been patched in a commit, wasn't adding up the clock speeds right. Just working on the other three now.
Sorry for not providing a fair competition :p
